
title: "HIDE Lab"
description: "Research in Deceptive AI"
baseurl: ""  # Leave this empty unless your site is hosted in a subdirectory
url: "https://hide-lab.github.io/"  # Your GitHub Pages URL

# Include these options if using GitHub Pages
markdown: kramdown
theme: minima  # Or leave empty if you are not using a pre-built theme

plugins: ['jekyll/scholar']
scholar:
  style: apa
  source: _bibliography